### ISSUE TITLE
Saving Very Quickly

### ISSUE THREAD

**Issue by Jayshua83** [Liareth/StarfieldQuicksaveOnInterval#1] opened 2023-09-04 19:04 UTC
This program was working every 2 minutes as intended until today.

I did delete some of my saves yesterday but I thought it was working after that.

Now it is saving every 10 secs or so. VERY quickly. Not sure what would cause this?

**Comment by Liareth** [comment] 2023-09-04 20:39
I've just pushed a fix for this. I think it was caused by SFSE backing up quicksave files (so it was detecting the wrong file). Give the latest release another shot and let me know how you get on!

**Comment by Jayshua83** [comment] 2023-09-04 20:48
Very odd since I haven't started using SFSE yet. But I am installing it today, but maybe this all will fix my issue regardless!

**Closed as completed** 2023-09-09 06:50 UTC
